# Generated by Django 2.2.3 on 2019-10-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='programmers',
        ),
    ]
