# Generated by Django 2.2.3 on 2019-10-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_date',
            field=models.DateField(null=True),
        ),
    ]
