# Generated by Django 2.2.3 on 2019-10-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_project_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_date',
        ),
    ]
