# Generated by Django 2.2.3 on 2019-10-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20191014_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='register',
            name='second_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='register',
            name='third_name',
            field=models.CharField(max_length=150),
        ),
    ]
