# Generated by Django 2.2.3 on 2019-10-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20191014_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='second_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='third_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
