# Generated by Django 2.2.3 on 2019-10-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_auto_20191015_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='register',
            name='second_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='third_name',
            field=models.CharField(max_length=50),
        ),
    ]
