# Generated by Django 2.2.3 on 2019-10-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_auto_20191015_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
