# Generated by Django 2.2.3 on 2019-10-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_auto_20191015_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='second_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='third_name',
            field=models.CharField(max_length=50),
        ),
    ]
