# Generated by Django 2.2.3 on 2019-10-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_auto_20191016_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
