# Generated by Django 2.2.3 on 2019-10-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0023_bootstrapregister_cssregister_jqregister_jsregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BootstrapRegister',
        ),
        migrations.DeleteModel(
            name='CssRegister',
        ),
        migrations.DeleteModel(
            name='HtmlRegister',
        ),
        migrations.DeleteModel(
            name='JqRegister',
        ),
        migrations.DeleteModel(
            name='JsRegister',
        ),
    ]
