# Generated by Django 2.2.3 on 2019-10-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0028_programmers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmers',
            name='back_id_card',
        ),
        migrations.RemoveField(
            model_name='programmers',
            name='front_id_card',
        ),
    ]
