# Generated by Django 2.2.3 on 2019-10-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0029_auto_20191023_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_dep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.Department'),
            preserve_default=False,
        ),
    ]
