# Generated by Django 2.2.3 on 2019-10-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0031_auto_20191025_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_dep',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
