# Generated by Django 2.2.3 on 2019-10-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0032_project_project_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmers',
            name='prog_dep',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
